#index:
#    path: /
#    controller: App\Controller\DefaultController::index
mairie:
  resource: routes/mairie/routes.yaml
  prefix: /mairie

parti:
  resource: routes/parti/routes.yaml
  prefix: /parti

politicien:
  resource: routes/politicien/routes.yaml
  prefix: /politicien

affaire:
  resource: routes/affaire/routes.yaml
  prefix: /affaire

general_index:
  path: /
  controller: App\Controller\GeneralController::index

